# Generated by Django 5.1.4 on 2025-01-09 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NativeName",
            fields=[
                (
                    "language_code",
                    models.CharField(
                        help_text="ISO 639-1 language code",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "official",
                    models.CharField(
                        help_text="Official native name of the country",
                        max_length=255,
                    ),
                ),
                (
                    "common",
                    models.CharField(
                        help_text="Common native name of the country",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capital",
                    models.CharField(
                        help_text="Capital city of the country",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "lat",
                    models.FloatField(help_text="Latitude of the country"),
                ),
                (
                    "lng",
                    models.FloatField(help_text="Longitude of the country"),
                ),
                (
                    "area",
                    models.FloatField(
                        help_text="Area of the country in square kilometers"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        help_text="Timezone of the country", max_length=50
                    ),
                ),
                (
                    "continent",
                    models.CharField(
                        help_text="Continent where the country is located",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "unique_together": {("lat", "lng")},
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        help_text="Common name of the country",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "official_name",
                    models.CharField(
                        help_text="Official name of the country",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "flag_png",
                    models.URLField(help_text="URL to the PNG flag image"),
                ),
                (
                    "flag_svg",
                    models.URLField(help_text="URL to the SVG flag image"),
                ),
                (
                    "flag_alt",
                    models.TextField(
                        blank=True,
                        help_text="Alternative text for the flag",
                        null=True,
                    ),
                ),
                (
                    "population",
                    models.IntegerField(help_text="Population of the country"),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country",
                        to="country.location",
                    ),
                ),
                (
                    "native_names",
                    models.ManyToManyField(
                        help_text="Native names of the country in different languages",
                        to="country.nativename",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
    ]
